#!/usr/bin/env python3
"""Generate vimhex-contex-entry.add.reg and .remove.reg.

    python3 make-context-entry-reg.py                 # default install path
    python3 make-context-entry-reg.py 'D:\\tools\\hexpair'   # somewhere else

Why this is generated rather than hand-written: the paths in the entries
have to survive a DEFAULT install with nobody editing anything, and a plain
REG_SZ value does NOT expand %USERPROFILE% -- the shell would look for a
directory literally named "%USERPROFILE%". Environment variables in a
registry value need REG_EXPAND_SZ, which the .reg text format can only
express as `hex(2):` followed by the string's UTF-16LE bytes. That is
unreadable and unmaintainable by hand; it is fine to generate.

The expansion order works out, and it is worth writing down because it is
the part that could silently break: the shell expands the environment
variable when it READS the value, then substitutes %1 when it builds the
command line. After %USERPROFILE% is consumed as a pair, the only % left in
the string is the one in %1 -- a lone %, so it cannot be mis-paired into a
bogus variable name, and it reaches Explorer's own substitution intact.

Python 3.8+, standard library only, deterministic output.
"""

import sys
from pathlib import Path

# Vim on Windows keeps the user's runtime files in %USERPROFILE%\vimfiles
# (no underscore -- it is _vimrc for the file, but vimfiles for the
# directory), and README.md's install instructions put the plugin in the
# pack/plugins/start/ package directory under it. This default is the whole
# point of the exercise: a default install must import and work as-is.
DEFAULT_ROOT = r"%USERPROFILE%\vimfiles\pack\plugins\start\hexpair"

# The no-console launcher every entry goes through; see its own header.
LAUNCHER = "vimhex-launch.vbs"

HEADER_ADD = """\
; ===========================================================================
; vimhex-contex-entry.add.reg - Explorer context-menu entries for hexpair
;
; GENERATED by make-context-entry-reg.py -- do not edit by hand; re-run that
; instead. The values are REG_EXPAND_SZ (the hex(2): form below), which is
; the only registry string type that expands %USERPROFILE%; a plain REG_SZ
; would send the shell looking for a folder literally called that.
;
; Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
; URL:         https://github.com/michal-ruzicka/hexpair
; License:     Vim License - same terms as Vim itself (see LICENSE.md
;              or :help license); SPDX-License-Identifier: Vim
;
; Adds ONE right-click folder under HKEY_CURRENT_USER - no administrator
; rights needed, nobody else's account touched - holding three entries:
;
;   vimhex >  gvimhex this          the file you right-clicked, in hex
;             ---------------       (a separator)
;             gvimhexdiff left      remember this as the left-hand side
;             gvimhexdiff right     diff it against the remembered one
;
; The folder is a verb carrying "ExtendedSubCommandsKey" and no \\command of
; its own; the key it names ({submenu}) holds the children
; under its own \\shell. That indirection keeps all of this inside HKCU: the
; older "SubCommands" scheme resolves verbs against HKLM's CommandStore,
; which would need administrator rights. Children are ordered alphabetically
; by KEY NAME, hence the 10-/20-/30- prefixes, and the separator is
; "CommandFlags"=dword:20 (ECF_SEPARATORBEFORE) on the item under the rule.
;
; NOTHING FLASHES. Every entry goes through wscript.exe running
; vimhex-launch.vbs, which is a GUI-subsystem program: no console window is
; ever created, so there is no flash and - the reason it was done - nothing
; steals the focus from the file manager the menu was opened in. The .cmd
; runs hidden; if it fails, its output is shown in a message box instead of
; a console that has already closed. See vimhex-launch.vbs's own header.
;
; They run gvimhex.cmd / gvimhexdiff.cmd, not vimhex.cmd / vimhexdiff.cmd:
; those default to gVim, so no VIMHEX_VIM is needed in your environment.
;
; NOTHING TO EDIT for a default install. Just double-click this file, or
; run:  reg import vimhex-contex-entry.add.reg
;
; The plugin is expected at
;   {root}
; which is where README.md's "Windows: vimhex and vimhexdiff outside Vim"
; section installs it. Installed somewhere else? Re-generate rather than
; edit:  python3 make-context-entry-reg.py "D:\\your\\path\\hexpair"
;
; vimhex-contex-entry.remove.reg undoes exactly this again.
;
; On Windows 11 this is a "legacy" context menu, so it appears under
; "Show more options" (Shift+F10 goes straight there). File managers that
; use the classic menu - Total Commander, for one - show it directly.
;
; The three .ico files are generated too, by icons/build.py - see
; icons/design.py. Only the .ico output ships in the release tarball.
; ===========================================================================
"""

HEADER_REMOVE = """\
; ===========================================================================
; vimhex-contex-entry.remove.reg - undo vimhex-contex-entry.add.reg
;
; GENERATED by make-context-entry-reg.py -- do not edit by hand.
;
; Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
; URL:         https://github.com/michal-ruzicka/hexpair
; License:     Vim License - same terms as Vim itself (see LICENSE.md
;              or :help license); SPDX-License-Identifier: Vim
;
; Removes the Explorer context-menu folder vimhex-contex-entry.add.reg adds:
; the "vimhex" verb and the hexpair.ContextMenu key holding its children,
; each deleted whole with the leading "-" (which takes every subkey and
; value with it). It also removes the three top-level entries an OLDER
; version of add.reg created, so that upgrading does not leave them orphaned
; next to the new folder.
;
; No path in here at all; a key is removed by name, whatever its command
; line says, so this file undoes an add.reg generated for ANY install path.
;
; Double-click this file, or run:  reg import vimhex-contex-entry.remove.reg
; ===========================================================================
"""

# The submenu the three entries live in. A verb carrying
# "ExtendedSubCommandsKey" is a FOLDER rather than a command -- it must not
# have a \command subkey of its own -- and the key it names holds the
# children under its own \shell. That indirection is what keeps this
# entirely inside HKEY_CURRENT_USER: the older "SubCommands" scheme resolves
# its verbs against HKLM's CommandStore, which needs administrator rights.
# The named key is relative to HKEY_CLASSES_ROOT, and HKCU\Software\Classes
# is merged into that, so writing it there is enough.
SUBMENU_KEY = "hexpair.ContextMenu"
SUBMENU_LABEL = "vimhex"
SUBMENU_ICON = "hexpair-open.ico"

# Children are shown in ALPHABETICAL order of their key name, not in the
# order they are written here, which is what the numeric prefixes are for.
#
# key, caption, icon, .cmd, args, separator-before
ITEMS = [
    ("10-open", "gvimhex this", "hexpair-open.ico", "gvimhex.cmd", "", False),
    ("20-pick", "gvimhexdiff left", "hexpair-pick.ico", "gvimhexdiff.cmd",
     "/pick", True),
    ("30-with", "gvimhexdiff right", "hexpair-with.ico", "gvimhexdiff.cmd",
     "/with", False),
]

# ECF_SEPARATORBEFORE. "CommandFlags" is a DWORD on the item that is to have
# the horizontal rule drawn above it.
ECF_SEPARATORBEFORE = 0x20

# Keys an older version of this file created at the top level of the "*"
# context menu, before the submenu existed. .remove.reg deletes these too,
# so that upgrading does not leave three orphaned entries behind next to the
# new folder.
LEGACY_KEYS = ["hexpair", "hexpair-pick", "hexpair-with"]


def expand_sz(value, prefix=""):
    """Render a string as a .reg REG_EXPAND_SZ value: hex(2) of its
    UTF-16LE bytes, NUL-terminated, wrapped the way regedit itself wraps.

    `prefix` is what precedes this on its first line (`@=`, `"Icon"=`) --
    counted so that the first line stays inside the same width as the
    continuations, which are indented two spaces after a trailing
    backslash."""
    data = value.encode("utf-16-le") + b"\x00\x00"
    octets = ["%02x" % b for b in data]

    out = []
    line = prefix + "hex(2):"
    for i, octet in enumerate(octets):
        piece = octet + ("," if i < len(octets) - 1 else "")
        if len(line) + len(piece) > 76:
            out.append(line + "\\")
            line = "  "
        line += piece
    out.append(line)
    return "\n".join(out)


def build_add(root):
    lines = ["Windows Registry Editor Version 5.00", ""]
    lines.append(HEADER_ADD.format(root=root, submenu=SUBMENU_KEY))

    # The folder itself. No \command subkey: that is what makes it a folder
    # rather than something clickable.
    lines.append("[HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\vimhex]")
    lines.append('"MUIVerb"="%s"' % SUBMENU_LABEL)
    lines.append(expand_sz("%s\\icons\\%s" % (root, SUBMENU_ICON), '"Icon"='))
    # Plain REG_SZ on purpose: this names a registry key, not a path, so
    # there is nothing in it for the environment to expand.
    lines.append('"ExtendedSubCommandsKey"="%s"' % SUBMENU_KEY)
    lines.append("")

    for key, caption, icon, cmd, args, separator in ITEMS:
        # wscript.exe rather than cmd.exe: wscript is a GUI-subsystem
        # program, so no console window is ever created - no flash, and
        # nothing takes the focus away from the file manager the menu was
        # opened in. vimhex-launch.vbs runs the .cmd hidden and turns a
        # failure into a message box. See its header.
        command = '%%SystemRoot%%\\System32\\wscript.exe "%s\\%s" "%s\\%s"' % (
            root,
            LAUNCHER,
            root,
            cmd,
        )
        if args:
            command += ' "%s"' % args
        command += ' "%1"'

        item = "HKEY_CURRENT_USER\\Software\\Classes\\%s\\shell\\%s" % (
            SUBMENU_KEY,
            key,
        )
        lines.append("[%s]" % item)
        lines.append('"MUIVerb"="%s"' % caption)
        lines.append(expand_sz("%s\\icons\\%s" % (root, icon), '"Icon"='))
        if separator:
            lines.append('"CommandFlags"=dword:%08x' % ECF_SEPARATORBEFORE)
        lines.append("")
        lines.append("[%s\\command]" % item)
        lines.append(expand_sz(command, "@="))
        lines.append("")

    return "\n".join(lines)


def build_remove():
    lines = ["Windows Registry Editor Version 5.00", ""]
    lines.append(HEADER_REMOVE)

    lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\vimhex]")
    lines.append("")
    lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\%s]" % SUBMENU_KEY)
    lines.append("")

    lines.append("; Entries an older version put straight in the \"*\" menu,")
    lines.append("; removed too so an upgrade leaves nothing orphaned behind.")
    for key in LEGACY_KEYS:
        lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\%s]" % key)
        lines.append("")
    return "\n".join(lines)


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ROOT
    root = root.rstrip("\\")
    here = Path(__file__).resolve().parent

    for name, text in (
        ("vimhex-contex-entry.add.reg", build_add(root)),
        ("vimhex-contex-entry.remove.reg", build_remove()),
    ):
        # CRLF, like .gitattributes pins these files to.
        (here / name).write_bytes(text.replace("\n", "\r\n").encode("ascii"))
        print("%s: written for %s" % (name, root))


if __name__ == "__main__":
    main()
