#!/usr/bin/env python3
"""Generate vimhex-contex-entry.add.reg and .remove.reg.

    python3 make-context-entry-reg.py                 # default install path
    python3 make-context-entry-reg.py 'D:\\tools\\hexpair'   # somewhere else

Why this is generated rather than hand-written: the paths in the entries
have to survive a DEFAULT install with nobody editing anything, and a plain
REG_SZ value does NOT expand %USERPROFILE% -- the shell would look for a
directory literally named "%USERPROFILE%". Environment variables in a
registry value need REG_EXPAND_SZ, which the .reg text format can only
express as `hex(2):` followed by the string's UTF-16LE bytes. That is
unreadable and unmaintainable by hand; it is fine to generate.

The expansion order works out, and it is worth writing down because it is
the part that could silently break: the shell expands the environment
variable when it READS the value, then substitutes %1 when it builds the
command line. After %USERPROFILE% is consumed as a pair, the only % left in
the string is the one in %1 -- a lone %, so it cannot be mis-paired into a
bogus variable name, and it reaches Explorer's own substitution intact.

Python 3.8+, standard library only, deterministic output.
"""

import sys
from collections import namedtuple
from pathlib import Path

# Vim on Windows keeps the user's runtime files in %USERPROFILE%\vimfiles
# (no underscore -- it is _vimrc for the file, but vimfiles for the
# directory), and README.md's install instructions put the plugin in the
# pack/plugins/start/ package directory under it. This default is the whole
# point of the exercise: a default install must import and work as-is.
DEFAULT_ROOT = r"%USERPROFILE%\vimfiles\pack\plugins\start\hexpair"

HEADER_ADD = """\
; ===========================================================================
; vimhex-contex-entry.add.reg - Explorer context-menu entries for hexpair
;
; GENERATED by make-context-entry-reg.py -- do not edit by hand; re-run that
; instead. The values are REG_EXPAND_SZ (the hex(2): form below), which is
; the only registry string type that expands %USERPROFILE%; a plain REG_SZ
; would send the shell looking for a folder literally called that.
;
; Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
; URL:         https://github.com/michal-ruzicka/hexpair
; License:     Vim License - same terms as Vim itself (see LICENSE.md
;              or :help license); SPDX-License-Identifier: Vim
;
; Adds ONE right-click folder under HKEY_CURRENT_USER - no administrator
; rights needed, nobody else's account touched - holding eight entries:
;
;   vimhex >  vimhex this                  right-clicked file, in hex, Vim
;             gvimhex this                 the same, in gVim
;             ---------------------------  (a separator)
;             vimhexdiff select as left    left-hand side, in Vim
;             gvimhexdiff select as left   the same, in gVim
;             vimhexdiff select as right   right-hand side, in Vim
;             gvimhexdiff select as right  the same, in gVim
;             ---------------------------  (a separator)
;             vim this                     right-clicked file, plain Vim
;             gvim this                    the same, in plain gVim
;
; Every action is offered in both Vims because which one you want is not
; something a menu can guess, and the console half is the half nothing else
; offers: Vim's own installer adds a gVim entry to this menu and no console
; one at all.
;
; The last pair open the file NORMALLY - no hex view, no paging, no plugin
; involved - which is the ordinary "edit this file" the rest of the menu
; does not do. They run whatever `vim` / `gvim` is on PATH; VIMHEX_VIM is
; not consulted, since that names the Vim hexpair's own commands use.
;
; The folder is a verb carrying "ExtendedSubCommandsKey" and no \\command of
; its own; the key it names ({submenu}) holds the children
; under its own \\shell. That indirection keeps all of this inside HKCU: the
; older "SubCommands" scheme resolves verbs against HKLM's CommandStore,
; which would need administrator rights. Children are ordered alphabetically
; by KEY NAME, hence the 10- to 80- prefixes, and each separator is
; "CommandFlags"=dword:20 (ECF_SEPARATORBEFORE) on the item under the rule.
;
; The two leading "[-...]" lines delete the folder and the child key before
; either is written again, so importing this over an OLDER hexpair leaves
; nothing of that release's menu behind. An import is a MERGE otherwise, and
; children that have since been renamed would stay in the menu beside the
; new ones, still clickable. It also makes re-importing this file a no-op
; rather than an accumulation.
;
; The two diff entries are SYMMETRIC: select either side first. Each records
; its side and stops; whichever completes the pair opens the comparison and
; clears both selections, so the next one starts clean. Selecting the same
; side twice just overwrites it.
;
; A console window appears for the moment the .cmd runs. That is accepted
; rather than worked around: hiding it needs either the Windows Script Host
; (whose "run hidden" pattern antivirus heuristics flag, and which Microsoft
; is removing from Windows) or an unsigned stub .exe (usually worse for
; antivirus, not better).
;
; The gvimhex* entries run gvimhex.cmd / gvimhexdiff.cmd, which default
; VIMHEX_VIM to "gvim", so the GUI opens with nothing set in your
; environment; the vimhex* entries run vimhex.cmd / vimhexdiff.cmd, which
; default to the console "vim" and get their console from the "cmd.exe /c"
; that starts them - that window is the editor's for as long as it runs.
; A VIMHEX_VIM already set in your environment overrides the default on
; both halves, which is what it is for.
;
; NOTHING TO EDIT for a default install. Just double-click this file, or
; run:  reg import vimhex-contex-entry.add.reg
;
; The plugin is expected at
;   {root}
; which is where README.md's "Windows: vimhex and vimhexdiff outside Vim"
; section installs it. Installed somewhere else? Re-generate rather than
; edit:  python3 make-context-entry-reg.py "D:\\your\\path\\hexpair"
;
; vimhex-contex-entry.remove.reg undoes exactly this again.
;
; On Windows 11 this is a "legacy" context menu, so it appears under
; "Show more options" (Shift+F10 goes straight there). File managers that
; use the classic menu - Total Commander, for one - show it directly.
;
; The four .ico files are generated too, by icons/build.py - see
; icons/design.py. Only the .ico output ships in the release tarball.
; ===========================================================================
"""

HEADER_REMOVE = """\
; ===========================================================================
; vimhex-contex-entry.remove.reg - undo vimhex-contex-entry.add.reg
;
; GENERATED by make-context-entry-reg.py -- do not edit by hand.
;
; Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
; URL:         https://github.com/michal-ruzicka/hexpair
; License:     Vim License - same terms as Vim itself (see LICENSE.md
;              or :help license); SPDX-License-Identifier: Vim
;
; Removes the Explorer context-menu folder vimhex-contex-entry.add.reg adds:
; the "vimhex" verb and the hexpair.ContextMenu key holding its children,
; each deleted whole with the leading "-" (which takes every subkey and
; value with it).
;
; No path in here at all; a key is removed by name, whatever its command
; line says, so this file undoes an add.reg generated for ANY install path.
;
; Double-click this file, or run:  reg import vimhex-contex-entry.remove.reg
; ===========================================================================
"""

# The submenu all the entries live in. A verb carrying
# "ExtendedSubCommandsKey" is a FOLDER rather than a command -- it must not
# have a \command subkey of its own -- and the key it names holds the
# children under its own \shell. That indirection is what keeps this
# entirely inside HKEY_CURRENT_USER: the older "SubCommands" scheme resolves
# its verbs against HKLM's CommandStore, which needs administrator rights.
# The named key is relative to HKEY_CLASSES_ROOT, and HKCU\Software\Classes
# is merged into that, so writing it there is enough.
SUBMENU_KEY = "hexpair.ContextMenu"
SUBMENU_LABEL = "vimhex"
SUBMENU_ICON = "hexpair-open.ico"

# Children are shown in ALPHABETICAL order of their key name, not in the
# order they are written here, which is what the numeric prefixes are for.
# Two digits throughout, so the order survives a ninth entry.
#
# `program` is either one of the plugin's own .cmd files, taken from the
# install directory (in_root), or a command name looked up on PATH.
#
# /left and /right may be used in either order: each records its side, and
# whichever completes the pair opens the comparison and clears both.
Item = namedtuple("Item", "key caption icon program args in_root separator")

# Each action twice, console Vim first and gVim second: the console half is
# the one nothing else offers, since Vim's own installer contributes a gVim
# entry to this menu and no console entry at all. The pair differ in nothing
# but which command they call, and the ICON says which ACTION rather than
# which Vim - a console/GUI difference drawn at 16px would be a guess about
# what a user can read, and the caption already spells it out.
#
# The last pair are not hexpair at all: they open the file the ordinary way,
# in a plain Vim with no hex view and no paging, which is the one thing a
# menu full of hex verbs could not otherwise do. They are also the only
# entries with no .cmd of the plugin's behind them, so they take `vim` and
# `gvim` from PATH -- the same names vimhex.cmd/gvimhex.cmd default
# VIMHEX_VIM to, but read straight rather than through that variable: it
# selects the Vim hexpair's commands open, and these two are deliberately
# outside hexpair.
ITEMS = [
    Item("10-open-vim", "vimhex this", "hexpair-open.ico",
         "vimhex.cmd", "", True, False),
    Item("20-open-gvim", "gvimhex this", "hexpair-open.ico",
         "gvimhex.cmd", "", True, False),
    Item("30-left-vim", "vimhexdiff select as left", "hexpair-pick.ico",
         "vimhexdiff.cmd", "/left", True, True),
    Item("40-left-gvim", "gvimhexdiff select as left", "hexpair-pick.ico",
         "gvimhexdiff.cmd", "/left", True, False),
    Item("50-right-vim", "vimhexdiff select as right", "hexpair-with.ico",
         "vimhexdiff.cmd", "/right", True, False),
    Item("60-right-gvim", "gvimhexdiff select as right", "hexpair-with.ico",
         "gvimhexdiff.cmd", "/right", True, False),
    Item("70-plain-vim", "vim this", "hexpair-vim.ico",
         "vim", "", False, True),
    Item("80-plain-gvim", "gvim this", "hexpair-vim.ico",
         "gvim", "", False, False),
]

# ECF_SEPARATORBEFORE. "CommandFlags" is a DWORD on the item that is to have
# the horizontal rule drawn above it.
ECF_SEPARATORBEFORE = 0x20


def expand_sz(value, prefix=""):
    """Render a string as a .reg REG_EXPAND_SZ value: hex(2) of its
    UTF-16LE bytes, NUL-terminated, wrapped the way regedit itself wraps.

    `prefix` is what precedes this on its first line (`@=`, `"Icon"=`) --
    counted so that the first line stays inside the same width as the
    continuations, which are indented two spaces after a trailing
    backslash."""
    data = value.encode("utf-16-le") + b"\x00\x00"
    octets = ["%02x" % b for b in data]

    out = []
    line = prefix + "hex(2):"
    for i, octet in enumerate(octets):
        piece = octet + ("," if i < len(octets) - 1 else "")
        if len(line) + len(piece) > 76:
            out.append(line + "\\")
            line = "  "
        line += piece
    out.append(line)
    return "\n".join(out)


def build_add(root):
    lines = ["Windows Registry Editor Version 5.00", ""]
    lines.append(HEADER_ADD.format(root=root, submenu=SUBMENU_KEY))

    # Whatever an EARLIER hexpair left here, removed before this one writes
    # its own -- the same two deletions remove.reg makes, and by name for
    # the same reason: "[-key]" takes every subkey and value with it, so it
    # does not matter what the previous release called its children. An
    # import is a merge otherwise, and a child that has since been renamed
    # would stay in the menu next to the new one, still clickable and still
    # running the command it was written with. v2.3.0 was the first release
    # whose submenu a user can have installed, so this is not hypothetical.
    #
    # regedit and `reg import` both apply a file top to bottom, which is
    # what makes delete-then-create in ONE file work.
    lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\vimhex]")
    lines.append("")
    lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\%s]" % SUBMENU_KEY)
    lines.append("")

    # The folder itself. No \command subkey: that is what makes it a folder
    # rather than something clickable.
    lines.append("[HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\vimhex]")
    lines.append('"MUIVerb"="%s"' % SUBMENU_LABEL)
    lines.append(expand_sz("%s\\icons\\%s" % (root, SUBMENU_ICON), '"Icon"='))
    # Plain REG_SZ on purpose: this names a registry key, not a path, so
    # there is nothing in it for the environment to expand.
    lines.append('"ExtendedSubCommandsKey"="%s"' % SUBMENU_KEY)
    lines.append("")

    for entry in ITEMS:
        # cmd.exe, and the console window it briefly creates, is accepted
        # rather than worked around. A wscript.exe/.vbs launcher did hide it,
        # but "run a command with a hidden window" through the Windows Script
        # Host is one of the shapes antivirus heuristics look for, and
        # VBScript is on its way out of Windows (Feature on Demand since
        # 11 24H2, removal announced). The other way out is a GUI-subsystem
        # stub .exe, which means shipping an unsigned binary - usually WORSE
        # for antivirus, not better. The maintainer's call, after weighing
        # all three: take the flash.
        #
        # The outer pair of quotes is cmd.exe's own rule 2 (strip the outer
        # pair, run the rest), which is what lets the .cmd path and the file
        # name each contain spaces.
        #
        # The plain-Vim pair go through cmd.exe as well, though they have no
        # .cmd to run and gVim would need no console: it keeps ONE quoting
        # story for the whole menu, and it is what makes `vim` and `gvim`
        # bare names resolvable at all -- PATH lookup, and the .bat stubs a
        # Vim install may put there, are the shell's job and not the
        # registry's.
        program = "%s\\%s" % (root, entry.program) if entry.in_root \
            else entry.program
        command = 'cmd.exe /c ""%s"' % program
        if entry.args:
            command += ' "%s"' % entry.args
        command += ' "%1""'

        item = "HKEY_CURRENT_USER\\Software\\Classes\\%s\\shell\\%s" % (
            SUBMENU_KEY,
            entry.key,
        )
        lines.append("[%s]" % item)
        lines.append('"MUIVerb"="%s"' % entry.caption)
        lines.append(expand_sz("%s\\icons\\%s" % (root, entry.icon),
                               '"Icon"='))
        if entry.separator:
            lines.append('"CommandFlags"=dword:%08x' % ECF_SEPARATORBEFORE)
        lines.append("")
        lines.append("[%s\\command]" % item)
        lines.append(expand_sz(command, "@="))
        lines.append("")

    return "\n".join(lines)


def build_remove():
    lines = ["Windows Registry Editor Version 5.00", ""]
    lines.append(HEADER_REMOVE)

    lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\vimhex]")
    lines.append("")
    lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\%s]" % SUBMENU_KEY)
    lines.append("")
    return "\n".join(lines)


USAGE = """\
usage: make-context-entry-reg.py [INSTALL_PATH]

Regenerates the two Explorer context-menu .reg files that ship with the
plugin. INSTALL_PATH is where hexpair is installed on the target machine,
in Windows form, and defaults to

    %s

Environment variables in it are expanded by Explorer at click time, not
here, so %%USERPROFILE%% and friends are meant to be written literally.
"""


def main():
    args = sys.argv[1:]
    # A path is what this takes, so an option-looking argument is a
    # mistake - and an expensive one to make silently, since the answer is
    # written straight over two files the release ships. `--help` used to
    # generate a menu pointing at a directory called "--help".
    if args and args[0].startswith("-"):
        out = sys.stdout if args[0] in ("-h", "--help") else sys.stderr
        out.write(USAGE % DEFAULT_ROOT)
        raise SystemExit(0 if args[0] in ("-h", "--help") else 2)
    if len(args) > 1:
        sys.stderr.write(USAGE % DEFAULT_ROOT)
        raise SystemExit(2)
    root = args[0] if args else DEFAULT_ROOT
    root = root.rstrip("\\")
    here = Path(__file__).resolve().parent

    for name, text in (
        ("vimhex-contex-entry.add.reg", build_add(root)),
        ("vimhex-contex-entry.remove.reg", build_remove()),
    ):
        # CRLF, like .gitattributes pins these files to.
        (here / name).write_bytes(text.replace("\n", "\r\n").encode("ascii"))
        print("%s: written for %s" % (name, root))


if __name__ == "__main__":
    main()
