#!/usr/bin/env python3
"""Generate vimhex-contex-entry.add.reg and .remove.reg.

    python3 make-context-entry-reg.py                 # default install path
    python3 make-context-entry-reg.py 'D:\\tools\\hexpair'   # somewhere else

Why this is generated rather than hand-written: the paths in the entries
have to survive a DEFAULT install with nobody editing anything, and a plain
REG_SZ value does NOT expand %USERPROFILE% -- the shell would look for a
directory literally named "%USERPROFILE%". Environment variables in a
registry value need REG_EXPAND_SZ, which the .reg text format can only
express as `hex(2):` followed by the string's UTF-16LE bytes. That is
unreadable and unmaintainable by hand; it is fine to generate.

The expansion order works out, and it is worth writing down because it is
the part that could silently break: the shell expands the environment
variable when it READS the value, then substitutes %1 when it builds the
command line. After %USERPROFILE% is consumed as a pair, the only % left in
the string is the one in %1 -- a lone %, so it cannot be mis-paired into a
bogus variable name, and it reaches Explorer's own substitution intact.

Python 3.8+, standard library only, deterministic output.
"""

import sys
from pathlib import Path

# Vim on Windows keeps the user's runtime files in %USERPROFILE%\vimfiles
# (no underscore -- it is _vimrc for the file, but vimfiles for the
# directory), and README.md's install instructions put the plugin in the
# pack/plugins/start/ package directory under it. This default is the whole
# point of the exercise: a default install must import and work as-is.
DEFAULT_ROOT = r"%USERPROFILE%\vimfiles\pack\plugins\start\hexpair"

HEADER_ADD = """\
; ===========================================================================
; vimhex-contex-entry.add.reg - Explorer context-menu entries for hexpair
;
; GENERATED by make-context-entry-reg.py -- do not edit by hand; re-run that
; instead. The values are REG_EXPAND_SZ (the hex(2): form below), which is
; the only registry string type that expands %USERPROFILE%; a plain REG_SZ
; would send the shell looking for a folder literally called that.
;
; Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
; URL:         https://github.com/michal-ruzicka/hexpair
; License:     Vim License - same terms as Vim itself (see LICENSE.md
;              or :help license); SPDX-License-Identifier: Vim
;
; Adds three right-click entries under HKEY_CURRENT_USER - no administrator
; rights needed, nobody else's account touched:
;
;   Open in hexpair              gvimhex.cmd on the file you right-clicked
;   Hex diff: select left side   gvimhexdiff.cmd /pick  on the first file
;   Hex diff: against selected   gvimhexdiff.cmd /with  on the second file
;
; They call gvimhex.cmd / gvimhexdiff.cmd, not vimhex.cmd / vimhexdiff.cmd -
; a context-menu verb has no console window to run the console Vim in, and
; gvimhex.cmd/gvimhexdiff.cmd already default to gVim for exactly that
; reason, without needing VIMHEX_VIM set in your user environment.
;
; NOTHING TO EDIT for a default install. Just double-click this file, or
; run:  reg import vimhex-contex-entry.add.reg
;
; The plugin is expected at
;   {root}
; which is where README.md's "Windows: vimhex and vimhexdiff outside Vim"
; section installs it. Installed somewhere else? Re-generate rather than
; edit:  python3 make-context-entry-reg.py "D:\\your\\path\\hexpair"
;
; vimhex-contex-entry.remove.reg undoes exactly this again. A console
; window appears for a fraction of a second while gvimhex.cmd/
; gvimhexdiff.cmd itself runs - see README.md for why. If it appears and
; disappears WITHOUT gVim ever showing up, gvimhex.cmd/gvimhexdiff.cmd
; pause on that failure instead of racing the window closed - re-run once
; more and read what they say (most likely: gvim.exe is not on PATH; set
; VIMHEX_VIM to its full path in your user environment).
;
; The three .ico files are generated too, by icons/build.py - see
; icons/design.py. Only the .ico output ships in the release tarball.
; ===========================================================================
"""

HEADER_REMOVE = """\
; ===========================================================================
; vimhex-contex-entry.remove.reg - undo vimhex-contex-entry.add.reg
;
; GENERATED by make-context-entry-reg.py -- do not edit by hand.
;
; Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
; URL:         https://github.com/michal-ruzicka/hexpair
; License:     Vim License - same terms as Vim itself (see LICENSE.md
;              or :help license); SPDX-License-Identifier: Vim
;
; Removes the three Explorer context-menu entries vimhex-contex-entry.add.reg
; adds - the "hexpair", "hexpair-pick" and "hexpair-with" keys, each with its
; own "command" subkey, deleted whole with the leading "-". No path in here
; at all; a key is removed by name, whatever its command line says, so this
; file undoes an add.reg generated for ANY install path.
;
; Double-click this file, or run:  reg import vimhex-contex-entry.remove.reg
; ===========================================================================
"""

# verb key, menu caption (& marks the accelerator), icon file, .cmd + args
VERBS = [
    ("hexpair", "Open in he&xpair", "hexpair-open.ico", "gvimhex.cmd", ""),
    (
        "hexpair-pick",
        "Hex diff: &select left side",
        "hexpair-pick.ico",
        "gvimhexdiff.cmd",
        "/pick ",
    ),
    (
        "hexpair-with",
        "Hex diff: &against selected",
        "hexpair-with.ico",
        "gvimhexdiff.cmd",
        "/with ",
    ),
]


def expand_sz(value, prefix=""):
    """Render a string as a .reg REG_EXPAND_SZ value: hex(2) of its
    UTF-16LE bytes, NUL-terminated, wrapped the way regedit itself wraps.

    `prefix` is what precedes this on its first line (`@=`, `"Icon"=`) --
    counted so that the first line stays inside the same width as the
    continuations, which are indented two spaces after a trailing
    backslash."""
    data = value.encode("utf-16-le") + b"\x00\x00"
    octets = ["%02x" % b for b in data]

    out = []
    line = prefix + "hex(2):"
    for i, octet in enumerate(octets):
        piece = octet + ("," if i < len(octets) - 1 else "")
        if len(line) + len(piece) > 76:
            out.append(line + "\\")
            line = "  "
        line += piece
    out.append(line)
    return "\n".join(out)


def build_add(root):
    lines = ["Windows Registry Editor Version 5.00", ""]
    lines.append(HEADER_ADD.format(root=root))

    for key, caption, icon, cmd, args in VERBS:
        # The command: cmd.exe /c ""<path to .cmd>" [/pick |/with ]"%1""
        # The outer pair of quotes is cmd.exe's own rule 2 (strip the outer
        # pair, run the rest), which is what lets both the .cmd path and the
        # file name contain spaces.
        command = 'cmd.exe /c ""%s\\%s" %s"%%1""' % (root, cmd, args)
        icon_path = "%s\\icons\\%s" % (root, icon)

        lines.append("[HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\%s]" % key)
        lines.append('@="%s"' % caption)
        lines.append(expand_sz(icon_path, '"Icon"='))
        lines.append("")
        lines.append(
            "[HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\%s\\command]" % key
        )
        lines.append(expand_sz(command, "@="))
        lines.append("")

    return "\n".join(lines)


def build_remove():
    lines = ["Windows Registry Editor Version 5.00", ""]
    lines.append(HEADER_REMOVE)
    for key, _, _, _, _ in VERBS:
        lines.append("[-HKEY_CURRENT_USER\\Software\\Classes\\*\\shell\\%s]" % key)
        lines.append("")
    return "\n".join(lines)


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ROOT
    root = root.rstrip("\\")
    here = Path(__file__).resolve().parent

    for name, text in (
        ("vimhex-contex-entry.add.reg", build_add(root)),
        ("vimhex-contex-entry.remove.reg", build_remove()),
    ):
        # CRLF, like .gitattributes pins these files to.
        (here / name).write_bytes(text.replace("\n", "\r\n").encode("ascii"))
        print("%s: written for %s" % (name, root))


if __name__ == "__main__":
    main()
