#!/usr/bin/env python3
"""Regenerate hexpair's Unicode block table from the Unicode Character Database.

Maintainer:  Michal Ruzicka <ruzicka.mich@gmail.com>
URL:         https://github.com/michal-ruzicka/hexpair
License:     Vim License - same terms as Vim itself (see LICENSE.md
             or :help license); SPDX-License-Identifier: Vim

    ./make-unicode-blocks.py [PATH_TO_Blocks.txt]

Rewrites the region between the two markers in plugin/hexpair.vim with the
block ranges from Blocks.txt, and touches nothing else in that file.

Without an argument it downloads Blocks.txt from the pinned URL below and
refuses to go on unless it hashes to EXPECTED_SHA256. The version is in the
URL and the digest is in this file, so a re-run either produces the same
table or stops - which is the same rule this project applies to every other
dependency, and the reason the table can be trusted without reading it.

Why a table at all, rather than asking Vim: Vim has no Unicode database.
charclass() knows three coarse classes and nothing about scripts or blocks,
and there is no name lookup at all. The block is what the data inspector can
honestly say about an arbitrary code point, and 338 ranges is what saying it
costs.

LICENSING, which is the part not to skip. Blocks.txt is under the Unicode
License V3 (SPDX: Unicode-3.0), which permits deriving from it and
distributing the result on the condition that its copyright and permission
notice appears with the copies OR in the associated documentation. NOTICE.md
carries that notice in full, names this file as what did the deriving, and
ships in every release tarball. Bumping UNICODE_VERSION here means updating
the version, URL and digest recorded there too.

Development-only, like make-context-entry-reg.py and icons/*.py: run by hand
when the Unicode version is bumped, never at package time and never on a
user's machine. It matches no pattern in the packaging test's shipped-files
glob, so it is correctly never expected in pack-release.py's FILES.
"""

import hashlib
import pathlib
import re
import sys
import urllib.request

UNICODE_VERSION = "16.0.0"
BLOCKS_URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/Blocks.txt"
EXPECTED_SHA256 = "f3907b395d410f1b97342292ca6bc83dd12eb4b205f2a0c48efdef99e517d7b0"

# `"\ ` and not a bare `"`: these sit INSIDE a continued list literal, and
# only the comment-continuation form is a comment there - a plain comment
# line ends the continuation and the rest becomes nonsense.
BEGIN = "        \"\\ >>> generated by make-unicode-blocks.py - do not edit below\n"
END = "        \"\\ <<< generated\n"

# 76, so that the widest generated line still fits the 80 columns the rest of
# plugin/hexpair.vim keeps to.
WIDTH = 76


def fetch() -> bytes:
    with urllib.request.urlopen(BLOCKS_URL, timeout=60) as response:
        return response.read()


def blocks(text: str):
    out = []
    for line in text.splitlines():
        match = re.match(r"^([0-9A-F]+)\.\.([0-9A-F]+);\s*(.+?)\s*$", line)
        if match:
            out.append((int(match.group(1), 16), int(match.group(2), 16),
                        match.group(3)))
    if not out:
        sys.exit("make-unicode-blocks: no block ranges in that file")
    # Sorted and disjoint is what the plugin's lookup assumes; Blocks.txt is
    # both, and checking says so rather than hoping.
    for (a_start, a_end, _), (b_start, _, _) in zip(out, out[1:]):
        if not a_start <= a_end < b_start:
            sys.exit(f"make-unicode-blocks: ranges overlap at {a_start:X}")
    return out


def vim_lines(rows):
    lines, current = [], "        \\ "
    for start, end, name in rows:
        # A name with an apostrophe would need doubling inside a Vim
        # single-quoted string. None has one today; this is here so that a
        # future one cannot arrive silently wrong.
        item = "[0x%X,0x%X,'%s']," % (start, end, name.replace("'", "''"))
        if len(current) + len(item) > WIDTH:
            lines.append(current.rstrip())
            current = "        \\ "
        current += item + " "
    lines.append(current.rstrip())
    return lines


def main() -> None:
    root = pathlib.Path(__file__).resolve().parent
    if len(sys.argv) > 1:
        raw = pathlib.Path(sys.argv[1]).read_bytes()
        print(f"reading {sys.argv[1]} (sha256 {hashlib.sha256(raw).hexdigest()})")
    else:
        print(f"fetching {BLOCKS_URL}")
        raw = fetch()
        got = hashlib.sha256(raw).hexdigest()
        if got != EXPECTED_SHA256:
            sys.exit(f"make-unicode-blocks: {BLOCKS_URL} has sha256 {got}, "
                     f"expected {EXPECTED_SHA256}")

    rows = blocks(raw.decode("utf-8"))
    body = vim_lines(rows)

    plugin = root / "plugin" / "hexpair.vim"
    text = plugin.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"make-unicode-blocks: markers not found in {plugin}")
    head = text[: text.index(BEGIN) + len(BEGIN)]
    tail = text[text.index(END):]
    generated = "".join(line + "\n" for line in body)
    plugin.write_text(head + generated + tail)

    print(f"{len(rows)} blocks, {len(body)} lines, Unicode {UNICODE_VERSION}")


if __name__ == "__main__":
    main()
